name: Build, Push and Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven (skip tests)
        run: mvn clean package -DskipTests

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: docker build -t yassinebendahui01/springboot-product-app:latest .

      - name: Push Docker Image
        run: docker push yassinebendahui01/springboot-product-app:latest

      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker pull yassinebendahui01/springboot-product-app:latest
            docker stop gestion-produits-app || true
            docker rm gestion-produits-app || true
            docker run -d --name gestion-produits-app -p 8080:8080 \
              -e SPRING_DATASOURCE_URL=jdbc:mysql://gpspdb.cdce6qcgk3ki.eu-west-3.rds.amazonaws.com:3306/gpspDB \
              -e SPRING_DATASOURCE_USERNAME=root \
              -e SPRING_DATASOURCE_PASSWORD=Y5sDtMmRXnDF80 \
              yassinebendahui01/springboot-product-app:latest

